### ISSUE TITLE
Not enough memes

### ISSUE THREAD

**Issue by sahiljain** [CoPilotUW/Orion#16]
@Jobair96 There are not enough memes. Please fix ASAP!

**Comment by AddySridhar95** [comment]
![giphy-downsized](https://user-images.githubusercontent.com/5092695/28354380-ab0c908a-6c2d-11e7-985d-d2fcf08f7df3.gif)

**Comment by acsant** [comment]
Dear @sahiljain ,
Thank-you for bringing this to our attention. We value our user's opinion and have worked hard to address this issue.
Here is a link to our latest meme addition to the repository: https://raw.githubusercontent.com/CoPilotUW/Orion/master/images/sahilmeme.png

Thank,
Akash
